# fly.toml file generated for autumn-wave-8062 on 2021-02-27T00:28:08-06:00

app = "autumn-wave-8062"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "ghcr.io/alexashley/302.fyi:1adaa3f"

[[services]]
  internal_port = 1234
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    port = "8080"
    restart_limit = 5
    timeout = "2s"
