# fly.toml file generated for autumn-wave-8062 on 2021-02-27T00:28:08-06:00

app = "autumn-wave-8062"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 1234
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 150
    soft_limit = 100

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    timeout = 2000
